Core concepts
selimatar/react-js-global-mentoring pull request #1
Opened 2023-03-20 18:11 UTC by selimatar

Hey, I created the components that were requested in the Core Concepts module. I know there are many things that need to be fixed but I followed all the course materials and I am working on my project quite busily. But I will try to fix it after. Also, I am quite excited about your comments. Thanks

2023-03-21 10:13 UTC, leandrocunha requested changes

2023-03-21 10:13 UTC, leandrocunha commented on src/components/Genre/GenreList.js
> +const GenreList = () => {
@selimatar to match the requirements you should pass 3 props for this component: genres list, current selected and callback. You did it partially so is just a case to make a light refactor to reach the requirements something like this:

```
const GenreList = ({ genreList, currentSelected, selectGenre }) => {
... 
}
```

so you can move the `genreList` to an external file and export it to be used through the props

instead to use `All` as initialState there you can pass the currentSelected that came from props, for example:

```
const [selectedGenre, setSelectedGenre] = useState(currentSelected);
```

and move the handleClick logic to an external function and it as a props, for example:

```
... 
const handleClick = index => setSelectedGenre(index)
...
```

2023-03-21 10:13 UTC, leandrocunha commented on src/components/Search/SearchForm.js
> +export class SearchForm extends React.Component{
@selimatar a light refactor here to match the requirements as well, so you should pass 2 props for this component: initialSearchQuery and callback

You used the default value coming from the state instead the initialSearchQuery, so just move things here

to the callback just move the handleSubmit logic to an external function, export and pass it through the props for this component.

2023-03-21 15:46 UTC, selimatar commented on src/App.js
>    return (
Done.

2023-03-21 15:46 UTC, selimatar commented on src/components/Counter/Counter.js
> +export class Counter extends React.Component {
Done.

2023-03-21 20:18 UTC, selimatar commented on src/components/Search/SearchForm.js
> +export class SearchForm extends React.Component{
Done.

2023-03-21 20:19 UTC, selimatar commented on src/components/Counter/Counter.js
> +export class Counter extends React.Component {
Done.

2023-03-21 21:05 UTC, selimatar commented on src/components/Counter/Counter.js
> +    return React.createElement(
Done.

2023-03-21 21:46 UTC, selimatar commented on src/components/Genre/GenreList.js
> +const GenreList = () => {
Done.

2023-03-22 21:04 UTC, leandrocunha requested changes

2023-03-22 21:04 UTC, leandrocunha commented on src/components/Search/SearchForm.js
> +export class SearchForm extends React.Component{
@selimatar I can't see the required props metioned above, here. Did you push the changes?

2023-03-24 06:38 UTC, selimatar commented on .vscode/settings.json
Hey, looks like it was added already

2023-03-24 06:38 UTC, selimatar commented on src/App.js
> +      <GenreList genreList={genreList} currentSelected={"All"} selectGenre={selectGenre}/>
Done.

2023-03-24 06:43 UTC, selimatar commented on src/components/Counter/Counter.js
> +      [
Done.

2023-03-24 06:44 UTC, selimatar commented on src/components/Genre/GenreList.js
> +                    return <Genre genre={genre} checkActive={checkActive} handleClick={handleClick}/>
Done.

2023-03-24 08:11 UTC, leandrocunha commented on .vscode/settings.json
@selimatar could you review it? I can't see the .vscode there

2023-03-24 10:45 UTC, selimatar commented on .vscode/settings.json
Here it is -> https://github.com/selimatar/react-js-global-mentoring/tree/core-concepts/.vscode

2023-03-24 12:25 UTC, selimatar commented on src/components/Search/SearchForm.js
> +export class SearchForm extends React.Component{
Done.

2023-03-30 20:46 UTC, leandrocunha requested changes

2023-03-30 20:46 UTC, leandrocunha commented on src/components/Search/SearchForm.js
> +function handleSubmit(value) {
@selimatar this function should be removed once you are using the same function that cames from App as a props.

2023-03-30 20:46 UTC, leandrocunha commented on src/components/Search/SearchForm.js
> +    this.handleChange = props.handleChange;
@selimatar this line 18 is overriding the line 17 where you are binding the `handleChange` method. You can remove it

2023-03-30 20:46 UTC, leandrocunha commented on src/components/Search/SearchForm.js
> +      <form style={{margin: "40px"}} onSubmit={handleSubmit(this.state.value)}>
@selimatar the `onSubmit` method should call the handleSubmit function from props, so you should do something like:
```
<form ... onSubmit={this.props.handleSubmit(this.state.value)}>
```

2023-03-31 07:02 UTC, selimatar commented on src/components/Search/SearchForm.js
> +      <form style={{margin: "40px"}} onSubmit={handleSubmit(this.state.value)}>
Done.

2023-03-31 18:06 UTC, leandrocunha requested changes

2023-03-31 18:06 UTC, leandrocunha commented on src/components/Genre/GenreList.js
> +                    return <Genre key={genre} genre={genre} checkActive={checkActive} handleClick={handleClick}/>
@selimatar you are using a genre object into the <Genre key /> props, this will cause an issue of multiples components using the same key.

You should do something like: `<Genre key={genre.id} ... />`

2023-03-31 19:16 UTC, selimatar commented on src/components/Genre/GenreList.js
> +                    return <Genre key={genre} genre={genre} checkActive={checkActive} handleClick={handleClick}/>
Done.

2023-03-31 19:42 UTC, leandrocunha approved these changes

2023-03-31 19:44 UTC, merged